### ISSUE TITLE
Limite de operação da atualização automática da Wikiscore

### ISSUE THREAD

**Issue by Danycdias** [WikiMovimentoBrasil/wikiconcursos#100]
Durante o evento Mais Mulheres, identificamos que a ferramenta Wikiscore não suporta a atualização automática de mais de 3k de artigos. Nós cadastramos cerca de 4~5k de artigos na Wikipédia e tivemos bugs com a atualização que nos impediram de lançar as parciais de forma independente, sem o suporte do WMB. Deixamos como sugestão a expansão do número de bytes suportados pela ferramenta.

**Comment by albertoleoncio** [comment]
Após a migração do sistema de PHP para Django, o sistema não está mais limitado pelo [max_execution_time](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time) do PHP e, neste momento, o limite de artigos por concurso é desconhecido. Nisso, estou fechando esse ticket como "resolvido".
