### ISSUE TITLE
As edições demoram entre um e cinco dias corridos para aparecerem na ferramenta Wikiscore

### ISSUE THREAD

**Issue by Danycdias** [WikiMovimentoBrasil/wikiconcursos#103]
Em 2022, criamos um relatório que [descrevia este problema](https://commons.wikimedia.org/w/index.php?title=File%3ARelat%C3%B3rio_de_utiliza%C3%A7%C3%A3o_da_ferramenta_Wikiconcursos_(WMB).pdf&page=7). Deixamos aqui esta mensagem para chamar a atenção ao fato de que o problema persiste. Durante o último concurso do Mais Diversidade 2024, notamos que ainda há um atraso considerável para que as edições apareçam na ferramenta. Esse intervalo impacta o acompanhamento e a validação das contribuições das parciais, por exemplo, e traz confusão aos participantes que fazem o controle manual de suas contribuições. Acreditamos que ajustes podem melhorar essa experiência e facilitar a participação. Agradecemos desde já por qualquer orientação ou atualização sobre isso!

**Comment by albertoleoncio** [comment]
Oi @Danycdias! Esse atraso não deveria estar acontecendo, principalmente porque o sistema mudou muito de 2022 para cá. Ocorreram alguns pequenos bugs no sistema de atualização mês passado, já que o projeto foi migrado de PHP para Django, mas foram pontuais e foram resolvidos adequadamente.

**Comment by Danycdias** [comment]
Oi, Alberto. Nós vamos continuar observando, então! Talvez tenha sido algo pontual. Se tiver mais indícios dos atrasos nos próximos eventos, notificamos vocês! Um abraço
