### ISSUE TITLE
Contabilização das edições com número de caracteres negativos ou resultantes em zero

### ISSUE THREAD

**Issue by Ederporto** [WikiMovimentoBrasil/wikiconcursos#12]
Pode ser útil avaliar e conceder pontos a participantes que limpam e arrumam artigos, embora suas edições resultem em um número negativo ou nulo de bytes modificados. Alguns usuários desejam que isso seja implementado. Por _default_, podemos continuar medindo somente bytes positivos não-nulos, mas deve ser dada a _opção_ de contabilização de bytes negativos e nulos, se não no momento de cadastro do wikiconcurso na ferramenta, como um switch "Ver edições nulas ou com número negativo de bytes", por exemplo.

**Comment by albertoleoncio** [comment]
Ver #3
