### ISSUE TITLE
Considerar edições negativas no cômputo dos pontos

### ISSUE THREAD

**Issue by albertoleoncio** [WikiMovimentoBrasil/wikiconcursos#3]
Normalmente as remoções de bytes não são computadas por motivos históricos:

- A ferramenta foi desenhada desde o primeiro Wikiconcurso para desconsiderar a remoção, já que as regras consideravam apenas a _adição de bytes_ pelo usuário e não o _aumento do saldo final de bytes_.
- Possibilitava que um usuário removesse inicialmente algum conteúdo ruim do artigo, antes de adicionar conteúdo melhor e referenciado.
- Não impede manipulação por ma-fé, já que poderia ocorrer casos onde um sock faria uma remoção prévia de conteúdo para que o participante readicionasse, ganhando pontos indevidos.
- Adicionaria certa complexidade: as remoções seriam avaliadas também? Como seria o processo?

Caso apenas o somatório de bytes seja avaliado, essa alteração seria simples de ser feita bastando adaptar a fórmula de cômputo, podendo ser personalizada por cada Wikiconcurso, mas é interessante analisar os prós e contras primeiro.

**Comment by Danycdias** [comment]
Olá! Seria realmente interessante ouvir a posição de mais pessoas e pensar nos diferentes casos que implicam estas mudanças.

Creio que neste caso, o que imagino é que todas as edições seriam avaliadas, tanto as de inserção de conteúdo quanto as de retirada. No Wikiconcurso chuva de bytes, passamos por duas situações que envolveram diferentes posicionamentos:
1) Verbetes existentes na Wikipédia que recebem ajustes de usuários com a retirada de bytes que englobam erros de formatação, espaços indevidos e/ou trechos não referenciados. Como essas edições não podem ser validadas através da ferramenta e foram consideradas pela equipe do Projeto como uma contribuição positiva aos verbetes, elas foram somadas manualmente para pontuação no Wikiconcurso.
2) Tradução automática de um verbete pela ferramenta beta. Neste caso, se alguém publicou 4 mil caracteres em uma edição e, em seguida, corrigiu o verbete, tirando 1.500 bytes na próxima edição, esta segunda edição não aparece na ferramenta Wikiconcursos. Esses ajustes geralmente são estilísticos, realizados em código-fonte, e não podem ser previstos, nem computam erro perante o processo de validação, mas conferem retirada significativa de bytes do produto final que já havia sido contabilizado. Estas edições tiveram que ser desconsideradas manualmente da pontuação final dos participantes do Wikiconcurso, pois a ferramenta não permite esse tipo de ajuste.
