### ISSUE TITLE
Flexibilizar pontuação por inserção de imagem

### ISSUE THREAD

**Issue by albertoleoncio** [WikiMovimentoBrasil/wikiconcursos#4]
Hoje, o parâmetro de inserção de imagem é _boolean_ (sim/não) por edição e a formula de cômputo apenas verifica se o usuário inseriu alguma imagem, em alguma edição, no artigo. Opções de flexibilização:

- Tornar parâmetro _integer_ (imagens por edição), necessita alteração na estrutura do banco de dados e várias alterações no código-fonte.
- Somar edições onde o usuário tenha inserido imagens, necessitando apenas a alteração da formula de cômputo, podendo ser personalizada por cada Wikiconcurso.
- Outras opções?

**Comment by Danycdias** [comment]
Olá. Não sei se compreendi bem o caráter dessa opções que foram colocadas, mas de qualquer forma deixo aqui algumas questões. Sem dúvidas, a ideia de esta opção das imagens poder ser personalizada de acordo com cada evento seria bem utilizada.
1) Seria interessante poder determinar o número de imagens inseridas em uma edição. 
2) As edições diferentes de um mesmo verbete não contabilizam o número de imagens inseridas, ainda que estas sejam colocadas de maneira independente. Por exemplo, um mesmo verbete recebeu duas edições, cada uma das edições tinham uma imagem e foram validadas com "sim". Neste caso, a ferramenta só está computando 1 imagem. Ao invés de 2. Isso é um erro? Ou é da própria caracterização da opção?
