### ISSUE TITLE
Adicionar extrato de edições na tela do avaliador

### ISSUE THREAD

**Issue by albertoleoncio** [WikiMovimentoBrasil/wikiconcursos#5]
O extrato pode ser obtido manualmente pelo desenvolvedor e extraído em planilha, entretanto é conveniente uma opção nativa para obtenção desse extrato.

- Apenas visualização? Na tela (HTML) ou em formato de planilha (CSV)?
- Incluir visualização e edição? Opções:
  - Todos poderão modificar as avaliações já realizadas?
  - Apenas o avaliador poderá modificar suas avaliações?
  - Diferenciar coordenador / avaliador (envolve gestão de credenciais)?

**Comment by Danycdias** [comment]
Olá. Não creio que haja a necessidade de descarregar as informações em planilhas se elas forem passíveis de visualização na ferramenta. Ressalto a importância da possibilidade de verificação das edições validadas, ou seja, uma página que contenha todas as edições que já passaram pela análise manual de um verificador, e que possua todas as informações pertinentes a cada edição, como número de bytes inseridos ou retirados, qual o utilizador que editou a página e o número de imagens da edição. Neste caso, seria uma página semelhante ao “Contador”, mas na qual fosse possível recuperar a visualização da edição e editá-la novamente, se assim fosse necessário. Além disso, creio que a reedição de uma validação poderia ser feita apenas pela pessoa que fez a primeira validação desta edição.
