### ISSUE TITLE
Integrar tradução com Translatewiki

### ISSUE THREAD

**Issue by Ederporto** [WikiMovimentoBrasil/wikiconcursos#90]
Seria possível integrar a tradução da ferramenta com o Translatewiki?

**Comment by albertoleoncio** [comment]
https://phabricator.wikimedia.org/T347244

**Comment by albertoleoncio** [comment]
https://translatewiki.net/wiki/Special:MessageGroupStats?group=wikiscore&messages=&suppressempty=1&language=fr&x=D#sortable:3=desc
