### ISSUE TITLE
Translation issue with message Wikimedia:Wikiscore-manage-remail/fr

### ISSUE THREAD

**Issue by Obscaeris** [WikiMovimentoBrasil/wikiconcursos#92]
URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=wikiscore-manage-remail&group=wikiscore&language=fr

Would be helpful to know what the $1 argument is, is it the name of the contest ? A code ?

**Comment by albertoleoncio** [comment]
@DrakeWK Hey! I just included the message documentation.

**Comment by Obscaeris** [comment]
> @DrakeWK Hey! I just included the message documentation.

Thanks will look at it now !
